### ISSUE TITLE
consider adding better focus states for keyboard users

### ISSUE THREAD

**Issue by skattabrain** [Qvant-lab/qui#12]
Nice work! 

While exploring your Storybook, I quickly noticed that focus states are not obvious enough for users that like to use the keyboard to tab around the page. Considering this story - https://qvant-lab.github.io/qui/?path=/story/components-qtabs-qtabs--q-tabs-story

You might want to consider using focus visible polyfills to only include more obvious focus state rings when using a keyboard on your various components.

https://github.com/WICG/focus-visible

https://github.com/csstools/postcss-focus-visible

**Comment by Tim152** [comment]
thank you! Sure, we will add more accessibility features
