### ISSUE TITLE
Support NuxtJS

### ISSUE THREAD

**Issue by arthur-vinchester** [Qvant-lab/qui#47]
Hi guys, your components are suitable for NuxtJS?
did not find any description in readme

**Comment by Tim152** [comment]
@arthur-vinchester Hi!
Actually, we haven't tried Qui with Nuxt, but I guess it should work fine, if you will try, get us to know pls

**Comment by Tim152** [comment]
So, we found out QBreadcrumbs only has problems with Nuxt, (will fix it later), all of the rest components work fine!
