### ISSUE TITLE
Question: Do you by any change have a CDN version for this?

### ISSUE THREAD

**Issue by Mashiane** [Qvant-lab/qui#78]
Hi there

Thanks for this awesome amazing lib. Do you happen to have a compiled version please that I can use with <script> tags?

Thanks

**Comment by Tim152** [comment]
Hi! Thank you for your feedback!
Yep, we have compiled v, you can use Qui with <script> tag via UNPKG. Check this: https://codepen.io/Tim152/pen/VwPEEPG

**Comment by Mashiane** [comment]
Awesome, thank you very very very much!
